language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - staging
    - trying
    - master

install:
  - pip install --upgrade setuptools
  - python setup.py build

script: "python test.py"
