language: python

matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: required

install:
  - pip install --upgrade setuptools pip

  - python setup.py build

script: "python test.py"

